# Generated by Django 5.0.6 on 2024-10-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_orderitem_order_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Delivered'), ('C', 'Canceled')], default='P', max_length=1),
        ),
    ]
